# Generated by Django 2.1.7 on 2019-03-12 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20190312_1307'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_category',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
