# Generated by Django 2.1.7 on 2019-03-13 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20190312_2301'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='book_category',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.RemoveField(
            model_name='book',
            name='author',
        ),
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.ManyToManyField(to='core.Author'),
        ),
        migrations.RemoveField(
            model_name='book',
            name='book_category',
        ),
        migrations.AddField(
            model_name='book',
            name='book_category',
            field=models.ManyToManyField(to='core.Category'),
        ),
    ]
