# Generated by Django 2.1.7 on 2019-03-13 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20190313_0912'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='name',
            new_name='author',
        ),
    ]
