# Generated by Django 2.1.7 on 2019-03-14 01:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20190313_1732'),
    ]

    operations = [
    ]
